version: "2"
linters:
  default: all
  disable:
    # Inappropriate
    - depguard
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - lll
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    exhaustive:
      ignore-enum-types: ^reflect\.Kind$
  exclusions:
    generated: strict
    rules:
      - linters:
          - errcheck
        # Taken from the default exclusions in v1
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - linters:
          - wrapcheck
        path: _test\.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/maxbrunet/minijinja-go)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/maxbrunet/minijinja-go
    golines:
      max-len: 80
  exclusions:
    generated: strict
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
